openapi: 3.1.0
info:
  title: S2
  version: 1.0.0
  license:
    name: Apache 2.0
servers:
  - url: http://127.0.0.1:4437
paths:
  /health:
    get:
      operationId: health
      summary: Health
      responses:
        "200":
          description: ""
          content:
            text/plain:
              schema:
                type: string
                example: ok
  /v1/basins:
    get:
      operationId: list_basins
      summary: List basins
      parameters:
        - $ref: "#/components/parameters/prefix"
        - $ref: "#/components/parameters/start_after"
        - $ref: "#/components/parameters/limit"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListBasinsResponse"
        "400":
          $ref: "#/components/responses/Error"
    post:
      operationId: create_basin
      summary: Create a basin
      parameters:
        - $ref: "#/components/parameters/s2-request-token"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBasinRequest"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasinInfo"
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasinInfo"
        "400":
          $ref: "#/components/responses/Error"
        "409":
          $ref: "#/components/responses/Error"
        "422":
          $ref: "#/components/responses/Error"
  /v1/basins/{basin}:
    parameters:
      - $ref: "#/components/parameters/basin"
    get:
      operationId: get_basin_config
      summary: Get basin configuration
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasinConfig"
        "404":
          $ref: "#/components/responses/Error"
    put:
      operationId: ensure_basin
      summary: Ensure a basin
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnsureBasinRequest"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasinInfo"
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasinInfo"
        "400":
          $ref: "#/components/responses/Error"
        "422":
          $ref: "#/components/responses/Error"
    patch:
      operationId: reconfigure_basin
      summary: Reconfigure a basin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BasinReconfiguration"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BasinConfig"
        "404":
          $ref: "#/components/responses/Error"
        "422":
          $ref: "#/components/responses/Error"
    delete:
      operationId: delete_basin
      summary: Delete a basin
      responses:
        "204":
          description: ""
        "404":
          $ref: "#/components/responses/Error"
  /v1/streams:
    parameters:
      - $ref: "#/components/parameters/s2-basin"
    get:
      operationId: list_streams
      summary: List streams
      parameters:
        - $ref: "#/components/parameters/prefix"
        - $ref: "#/components/parameters/start_after"
        - $ref: "#/components/parameters/limit"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListStreamsResponse"
        "400":
          $ref: "#/components/responses/Error"
        "404":
          $ref: "#/components/responses/Error"
    post:
      operationId: create_stream
      summary: Create a stream
      parameters:
        - $ref: "#/components/parameters/s2-request-token"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateStreamRequest"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StreamInfo"
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StreamInfo"
        "400":
          $ref: "#/components/responses/Error"
        "404":
          $ref: "#/components/responses/Error"
        "409":
          $ref: "#/components/responses/Error"
        "422":
          $ref: "#/components/responses/Error"
  /v1/streams/{stream}:
    parameters:
      - $ref: "#/components/parameters/s2-basin"
      - $ref: "#/components/parameters/stream"
    get:
      operationId: get_stream_config
      summary: Get stream configuration
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StreamConfig"
        "404":
          $ref: "#/components/responses/Error"
    put:
      operationId: ensure_stream
      summary: Ensure a stream
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/EnsureStreamRequest"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StreamInfo"
        "201":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StreamInfo"
        "400":
          $ref: "#/components/responses/Error"
        "404":
          $ref: "#/components/responses/Error"
        "422":
          $ref: "#/components/responses/Error"
    patch:
      operationId: reconfigure_stream
      summary: Reconfigure a stream
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StreamReconfiguration"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StreamConfig"
        "404":
          $ref: "#/components/responses/Error"
        "422":
          $ref: "#/components/responses/Error"
    delete:
      operationId: delete_stream
      summary: Delete a stream
      responses:
        "204":
          description: ""
        "404":
          $ref: "#/components/responses/Error"
  /v1/streams/{stream}/records:
    parameters:
      - $ref: "#/components/parameters/s2-basin"
      - $ref: "#/components/parameters/stream"
      - $ref: "#/components/parameters/s2-format"
    get:
      operationId: read
      summary: Read records
      parameters:
        - name: seq_num
          in: query
          schema:
            $ref: "#/components/schemas/u64"
        - name: timestamp
          in: query
          schema:
            $ref: "#/components/schemas/u64"
        - name: tail_offset
          in: query
          schema:
            type: integer
            format: int64
            minimum: 0
        - name: clamp
          in: query
          schema:
            type: boolean
        - name: count
          in: query
          schema:
            type: integer
            format: int64
            minimum: 0
        - name: bytes
          in: query
          schema:
            type: integer
            minimum: 0
        - name: until
          in: query
          schema:
            $ref: "#/components/schemas/u64"
        - name: wait
          in: query
          schema:
            type: integer
            format: int32
            minimum: 0
            maximum: 60
        - name: Last-Event-ID
          in: header
          schema:
            type: string
            pattern: "^[0-9]+,[0-9]+,[0-9]+$"
        - name: Accept
          in: header
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReadBatch"
            text/event-stream:
              schema:
                type: string
        "400":
          $ref: "#/components/responses/Error"
        "404":
          $ref: "#/components/responses/Error"
        "416":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TailResponse"
    post:
      operationId: append
      summary: Append records
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AppendInput"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppendAck"
        "400":
          $ref: "#/components/responses/Error"
        "404":
          $ref: "#/components/responses/Error"
        "412":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppendConditionFailed"
        "422":
          $ref: "#/components/responses/Error"
  /v1/streams/{stream}/records/tail:
    parameters:
      - $ref: "#/components/parameters/s2-basin"
      - $ref: "#/components/parameters/stream"
    get:
      operationId: check_tail
      summary: Check the tail
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TailResponse"
        "404":
          $ref: "#/components/responses/Error"
components:
  parameters:
    basin:
      name: basin
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/BasinName"
    stream:
      name: stream
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/StreamName"
    s2-basin:
      name: s2-basin
      in: header
      required: true
      schema:
        $ref: "#/components/schemas/BasinName"
    s2-format:
      name: s2-format
      in: header
      schema:
        $ref: "#/components/schemas/Format"
    s2-request-token:
      name: s2-request-token
      in: header
      schema:
        type: string
    prefix:
      name: prefix
      in: query
      schema:
        type: string
        default: ""
    start_after:
      name: start_after
      in: query
      schema:
        type: string
        default: ""
    limit:
      name: limit
      in: query
      schema:
        type: integer
        default: 1000
        maximum: 1000
        minimum: 0
  responses:
    Error:
      description: ""
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
  schemas:
    u64:
      type: integer
      format: int64
      minimum: 0
    BasinName:
      type: string
      minLength: 8
      maxLength: 48
      pattern: "^[a-z0-9]([a-z0-9-]{6,46})[a-z0-9]$"
    StreamName:
      type: string
      minLength: 1
      maxLength: 512
    Format:
      type: string
      enum: [raw, base64]
    ErrorInfo:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
        message:
          type: string
        resource:
          type: string
    BasinInfo:
      type: object
      required: [name, created_at]
      properties:
        name:
          $ref: "#/components/schemas/BasinName"
        location:
          type: ["string", "null"]
        created_at:
          type: string
          format: date-time
        deleted_at:
          type: ["string", "null"]
          format: date-time
        state:
          type: string
          enum: [active]
    StreamInfo:
      type: object
      required: [name, created_at]
      properties:
        name:
          $ref: "#/components/schemas/StreamName"
        created_at:
          type: string
          format: date-time
        deleted_at:
          type: ["string", "null"]
          format: date-time
        cipher:
          type: ["string", "null"]
    ListBasinsResponse:
      type: object
      required: [basins, has_more]
      properties:
        basins:
          type: array
          items:
            $ref: "#/components/schemas/BasinInfo"
          maxItems: 1000
        has_more:
          type: boolean
    ListStreamsResponse:
      type: object
      required: [streams, has_more]
      properties:
        streams:
          type: array
          items:
            $ref: "#/components/schemas/StreamInfo"
          maxItems: 1000
        has_more:
          type: boolean
    CreateBasinRequest:
      type: object
      required: [basin]
      properties:
        basin:
          $ref: "#/components/schemas/BasinName"
        config:
          $ref: "#/components/schemas/BasinConfig"
    EnsureBasinRequest:
      type: object
      properties:
        config:
          $ref: "#/components/schemas/BasinConfig"
    CreateStreamRequest:
      type: object
      required: [stream]
      properties:
        stream:
          $ref: "#/components/schemas/StreamName"
        config:
          $ref: "#/components/schemas/StreamConfig"
    EnsureStreamRequest:
      type: object
      properties:
        config:
          $ref: "#/components/schemas/StreamConfig"
    BasinConfig:
      type: object
      properties:
        create_stream_on_append:
          type: boolean
          default: false
        create_stream_on_read:
          type: boolean
          default: false
        default_stream_config:
          $ref: "#/components/schemas/StreamConfig"
    BasinReconfiguration:
      type: object
      properties:
        create_stream_on_append:
          type: ["boolean", "null"]
        create_stream_on_read:
          type: ["boolean", "null"]
        default_stream_config:
          $ref: "#/components/schemas/StreamReconfiguration"
    StreamConfig:
      type: object
      properties:
        storage_class:
          $ref: "#/components/schemas/StorageClass"
        retention_policy:
          $ref: "#/components/schemas/RetentionPolicy"
        timestamping:
          $ref: "#/components/schemas/TimestampingConfig"
        delete_on_empty:
          $ref: "#/components/schemas/DeleteOnEmptyConfig"
    StreamReconfiguration:
      type: object
      properties:
        storage_class:
          $ref: "#/components/schemas/StorageClass"
        retention_policy:
          $ref: "#/components/schemas/RetentionPolicy"
        timestamping:
          $ref: "#/components/schemas/TimestampingReconfiguration"
        delete_on_empty:
          $ref: "#/components/schemas/DeleteOnEmptyReconfiguration"
    StorageClass:
      type: string
      enum: [standard, express]
    RetentionPolicy:
      oneOf:
        - type: object
          required: [age]
          properties:
            age:
              type: integer
              format: int64
              minimum: 1
        - type: object
          required: [infinite]
          properties:
            infinite:
              type: object
    TimestampingConfig:
      type: object
      properties:
        mode:
          $ref: "#/components/schemas/TimestampingMode"
        uncapped:
          type: boolean
    TimestampingReconfiguration:
      type: object
      properties:
        mode:
          $ref: "#/components/schemas/TimestampingMode"
        uncapped:
          type: ["boolean", "null"]
    TimestampingMode:
      type: string
      enum: [client-prefer, client-require, arrival]
    DeleteOnEmptyConfig:
      type: object
      properties:
        min_age_secs:
          type: integer
          format: int64
          minimum: 0
    DeleteOnEmptyReconfiguration:
      type: object
      properties:
        min_age_secs:
          type: ["integer", "null"]
          format: int64
          minimum: 0
    Header:
      type: array
      items:
        type: string
      minItems: 2
      maxItems: 2
    AppendRecord:
      type: object
      properties:
        timestamp:
          $ref: "#/components/schemas/u64"
        headers:
          type: array
          items:
            $ref: "#/components/schemas/Header"
        body:
          type: string
    AppendInput:
      type: object
      required: [records]
      properties:
        records:
          type: array
          items:
            $ref: "#/components/schemas/AppendRecord"
          minItems: 1
          maxItems: 1000
        match_seq_num:
          $ref: "#/components/schemas/u64"
        fencing_token:
          type: string
          maxLength: 36
    StreamPosition:
      type: object
      required: [seq_num, timestamp]
      properties:
        seq_num:
          $ref: "#/components/schemas/u64"
        timestamp:
          $ref: "#/components/schemas/u64"
    AppendAck:
      type: object
      required: [start, end, tail]
      properties:
        start:
          $ref: "#/components/schemas/StreamPosition"
        end:
          $ref: "#/components/schemas/StreamPosition"
        tail:
          $ref: "#/components/schemas/StreamPosition"
    AppendConditionFailed:
      oneOf:
        - type: object
          required: [fencing_token_mismatch]
          properties:
            fencing_token_mismatch:
              type: string
        - type: object
          required: [seq_num_mismatch]
          properties:
            seq_num_mismatch:
              $ref: "#/components/schemas/u64"
    SequencedRecord:
      type: object
      required: [seq_num, timestamp]
      properties:
        seq_num:
          $ref: "#/components/schemas/u64"
        timestamp:
          $ref: "#/components/schemas/u64"
        headers:
          type: array
          items:
            $ref: "#/components/schemas/Header"
        body:
          type: string
    ReadBatch:
      type: object
      required: [records]
      properties:
        records:
          type: array
          items:
            $ref: "#/components/schemas/SequencedRecord"
        tail:
          $ref: "#/components/schemas/StreamPosition"
    TailResponse:
      type: object
      required: [tail]
      properties:
        tail:
          $ref: "#/components/schemas/StreamPosition"
